version: '3.1'
services:
  app:
    networks:
      - plex-calendar
    image: 'plex-calendar'
    build: .
    restart: unless-stopped
    ports:
      - 4545:5000
    environment:
      PORT: 5000

      PLEX_HOSTNAME: $PLEX_HOSTNAME
      PLEX_PORT: $PLEX_PORT

    volumes:
      - ./logs:/home/plex-calendar/logs

networks:
  plex-calendar: